### ISSUE TITLE
Deployment is failing - Timeout of 2000ms exceeded.

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/microsoft-onedrive-component#18]
Component is not possible to deploy into more restricted systems. It fails the tests:
```
       1) Upsert File
       Returns response for uploaded file:
       Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/tmp/build/spec/actions/upsertFile.spec.js)
       at listOnTimeout (internal/timers.js:549:17)
       at processTimers (internal/timers.js:492:7)



remote: npm ERR! Test failed.  See above for more details.

-----> Build failed

       We're sorry this build is failing! If you can't find the issue in component code,
       please submit a ticket so we can help: https://support.elastic.io
       You can also try upgrading Sailor to the most recent version. Check out
       https://www.npmjs.com/package/elasticio-sailor-nodejs

       Your elastic.io team
remote:
remote:
remote: Removing build container and slug
remote: Saving build
remote: Detaching from log stream
remote: Build failed
remote: Error: Appbuilder failed with code 1
remote: Error: Appbuilder failed with code 1
remote:     at ChildProcess.<anonymous> (/home/node/gitreceiver/src/lib/builder.js:74:31)
remote:     at ChildProcess.emit (events.js:310:20)
remote:     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
remote: {"name":"gitreceiver","hostname":"gitreceiver-7b85ccd445-xv2kk","pid":"4576","level":"50","err":{"message":"Appbuilder failed with code 1","name":"Error","stack":"Error: Appbuilder failed with code 1\n    at ChildProcess.<anonymous> (/home/node/gitreceiver/src/lib/builder.js:74:31)\n    at ChildProcess.emit (events.js:310:20)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)"},"msg":"Appbuilder failed with code 1","time":"2020-06-08T15:02:22.946Z","v":"0"}
To app-msp-test:ms-onedrive.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to '****@****:ms-onedrive.git'
```

**Comment by khanzadyan** [comment]
Update: 06.04.2021: Component is again failing to be deployed. The same error is happening. Used the recent version of the component.
